Repository Team-Haruchi/HARUCHI_SPRING, pull requests merged in 2024-07, with the labels that each got.

#3 [FEAT] enums & entity 설계
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/Expenditure.java
  src/main/java/umc/haruchi/domain/Income.java
  src/main/java/umc/haruchi/domain/Member.java
  src/main/java/umc/haruchi/domain/MemberToken.java
  src/main/java/umc/haruchi/domain/MonthBudget.java
  src/main/java/umc/haruchi/domain/PullMinusClosing.java
  src/main/java/umc/haruchi/domain/PushPlusClosing.java
  src/main/java/umc/haruchi/domain/enums/DayBudgetStatus.java
  src/main/java/umc/haruchi/domain/enums/LoginStatus.java
  src/main/java/umc/haruchi/domain/enums/RedistributionOption.java
  src/main/java/umc/haruchi/domain/mapping/BudgetRedistribution.java
Labels: :sparkles: Feat

#4 [CI] ci/cd 파이프라인 구축 및 RDS 연결 설정
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/umc/haruchi/domain/PullMinusClosing.java
  src/main/java/umc/haruchi/domain/PushPlusClosing.java
  src/main/resources/application.yml
Labels: :sparkles: Feat, :earth_asia: Deploy, :construction_worker: Ci

#5 [FIX] nginx.conf 파일 위치 수정
  .platform/nginx/nginx.conf
  src/main/java/umc/haruchi/web/controller/RootController.java
Labels: :hammer: Fix

#6 [FIX] nginx.conf 파일 위치 수정
  .platform/nginx.conf
Labels: :hammer: Fix

#7 [CI] client_max_body_size.conf 추가
  .platform/nginx/conf.d/client_max_body_size.conf
Labels: :earth_asia: Deploy, :construction_worker: Ci

#8 [FIX] health api 수정
  .github/workflows/dev_deploy.yml
  src/main/java/umc/haruchi/web/controller/RootController.java
Labels: :hammer: Fix

#9 [FIX] nginx timeout 설정
  .platform/nginx.conf
Labels: :hammer: Fix

#10 [FIX] gitIgnore 수정
  .gitignore
  src/main/resources/application.yml
Labels: :hammer: Fix

#11 [FIX] enums & entity 수정
  src/main/java/umc/haruchi/HaruchiApplication.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/Expenditure.java
  src/main/java/umc/haruchi/domain/Income.java
  src/main/java/umc/haruchi/domain/Member.java
  src/main/java/umc/haruchi/domain/MemberToken.java
  src/main/java/umc/haruchi/domain/MonthBudget.java
  src/main/java/umc/haruchi/domain/PullMinusClosing.java
  src/main/java/umc/haruchi/domain/PushPlusClosing.java
  src/main/java/umc/haruchi/domain/enums/ExpenditureCategory.java
  src/main/java/umc/haruchi/domain/enums/IncomeCategory.java
  src/main/java/umc/haruchi/domain/enums/LoginStatus.java
  src/main/java/umc/haruchi/domain/enums/MemberStatus.java
  src/main/java/umc/haruchi/domain/mapping/BudgetRedistribution.java
  src/main/java/umc/haruchi/repository/TempRepository.java
  src/main/java/umc/haruchi/service/TempService.java
Labels: :sparkles: Feat, :hammer: Fix

#14 [FEAT] 이메일 인증 방식 회원가입 API 구현
  build.gradle
  src/main/java/umc/haruchi/HaruchiApplication.java
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/haruchi/config/EmailConfig.java
  src/main/java/umc/haruchi/converter/MemberConverter.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/Member.java
  src/main/java/umc/haruchi/domain/common/BaseEntity.java
  src/main/java/umc/haruchi/repository/MemberRepository.java
  src/main/java/umc/haruchi/service/MemberService.java
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
  src/main/java/umc/haruchi/web/dto/MemberRequestDTO.java
  src/main/java/umc/haruchi/web/dto/MemberResponseDTO.java
  src/main/resources/application.yml
Labels: :bug: Bug, :sparkles: Feat, :hammer: Fix, :wrench: Chore

#16 [CI] AWS redis host 등록
  src/main/resources/application.yml
Labels: :earth_asia: Deploy, :construction_worker: Ci

#18 [FEAT] 하루 예산 금액 조회 API 구현
  src/main/java/umc/haruchi/apiPayload/ApiResponse.java
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/apiPayload/exception/handler/DayBudgetHandler.java
  src/main/java/umc/haruchi/apiPayload/exception/handler/MonthBudgetHandler.java
  src/main/java/umc/haruchi/converter/DayBudgetConverter.java
  src/main/java/umc/haruchi/repository/DayBudgetRepository.java
  src/main/java/umc/haruchi/repository/MonthBudgetRepository.java
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/web/controller/DayBudgetController.java
  src/main/java/umc/haruchi/web/dto/DayBudgetResponseDTO.java
Labels: :sparkles: Feat, :hammer: Fix

#24 [FEAT\ 수입 등록/삭제 API 구현
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/apiPayload/exception/handler/IncomeHandler.java
  src/main/java/umc/haruchi/converter/DayBudgetConverter.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/MonthBudget.java
  src/main/java/umc/haruchi/repository/IncomeRepository.java
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/web/controller/DayBudgetController.java
  src/main/java/umc/haruchi/web/dto/DayBudgetRequestDTO.java
  src/main/java/umc/haruchi/web/dto/DayBudgetResponseDTO.java
Labels: :sparkles: Feat, :hammer: Fix

#27 [FEAT] 넘겨쓰기/당겨쓰기 API 구현
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/apiPayload/exception/handler/BudgetRedistributionHandler.java
  src/main/java/umc/haruchi/config/login/auth/MemberDetail.java
  src/main/java/umc/haruchi/converter/BudgetRedistributionConverter.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/Member.java
  src/main/java/umc/haruchi/domain/PullMinusClosing.java
  src/main/java/umc/haruchi/domain/PushPlusClosing.java
  src/main/java/umc/haruchi/domain/mapping/BudgetRedistribution.java
  src/main/java/umc/haruchi/repository/PullMinusClosingRepository.java
  src/main/java/umc/haruchi/repository/PushPlusClosingRepository.java
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
  src/main/java/umc/haruchi/web/controller/BudgetRedistributionController.java
  src/main/java/umc/haruchi/web/dto/BudgetRedistributionRequestDTO.java
  src/main/java/umc/haruchi/web/dto/BudgetRedistributionResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#29 [FIX] errorStatus 추가 및 당겨쓰기 로직 수정
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
Labels: :hammer: Fix

#31 [FEAT] 회원 정보 조회 및 세이프박스 금액 조회 API 구현
  src/main/java/umc/haruchi/apiPayload/exception/handler/JwtExceptionHandler.java
  src/main/java/umc/haruchi/apiPayload/exception/handler/JwtExpiredHandler.java
  src/main/java/umc/haruchi/apiPayload/exception/handler/JwtInvalidHandler.java
  src/main/java/umc/haruchi/config/SwaggerConfig.java
  src/main/java/umc/haruchi/config/login/SecurityConfig.java
  src/main/java/umc/haruchi/config/login/jwt/JwtAccessDeniedHandler.java
  src/main/java/umc/haruchi/config/login/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/umc/haruchi/config/login/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/haruchi/config/login/jwt/JwtExceptionHandlerFilter.java
  src/main/java/umc/haruchi/config/login/jwt/JwtUtil.java
  src/main/java/umc/haruchi/service/MemberService.java
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
  src/main/java/umc/haruchi/web/dto/MemberResponseDTO.java
Labels: :sparkles: Feat, :art: Style, :hammer: Fix
