Repository Team-Haruchi/HARUCHI_SPRING, pull requests merged in 2024-08, with the labels that each got.

#33 [FIX] 리프레시 토큰을 엔티티 대신 redis에 저장하도록 수정
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/config/login/SecurityConfig.java
  src/main/java/umc/haruchi/config/login/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/haruchi/config/login/jwt/JwtTokenService.java
  src/main/java/umc/haruchi/config/login/jwt/JwtUtil.java
  src/main/java/umc/haruchi/config/redis/RedisConfig.java
  src/main/java/umc/haruchi/config/redis/RedisUtil.java
  src/main/java/umc/haruchi/converter/MemberConverter.java
  src/main/java/umc/haruchi/domain/Member.java
  src/main/java/umc/haruchi/domain/MemberToken.java
  src/main/java/umc/haruchi/domain/enums/MemberStatus.java
  src/main/java/umc/haruchi/repository/MemberTokenRepository.java
  src/main/java/umc/haruchi/service/MemberService.java
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
  src/main/java/umc/haruchi/web/dto/MemberRequestDTO.java
  src/main/java/umc/haruchi/web/dto/MemberResponseDTO.java
  src/main/resources/application.yml
Labels: :art: Style, :hammer: Fix

#35 [FEAT] 지출 마감, 1/n 경우 하루 분배 값 조회 API 구현
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/converter/BudgetRedistributionConverter.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/PullMinusClosing.java
  src/main/java/umc/haruchi/domain/PushPlusClosing.java
  src/main/java/umc/haruchi/domain/enums/RedistributionOption.java
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
  src/main/java/umc/haruchi/web/controller/BudgetRedistributionController.java
  src/main/java/umc/haruchi/web/dto/BudgetRedistributionRequestDTO.java
  src/main/java/umc/haruchi/web/dto/BudgetRedistributionResponseDTO.java
Labels: :sparkles: Feat

#32 [FEAT] 한달 예산 수정 API 구현
  src/main/java/umc/haruchi/HaruchiApplication.java
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/converter/DayBudgetConverter.java
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/Member.java
  src/main/java/umc/haruchi/domain/MonthBudget.java
  src/main/java/umc/haruchi/repository/DayBudgetRepository.java
  src/main/java/umc/haruchi/repository/MonthBudgetRepository.java
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/service/MemberService.java
  src/main/java/umc/haruchi/service/MonthBudgetService.java
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
  src/main/java/umc/haruchi/web/controller/MonthBudgetController.java
  src/main/java/umc/haruchi/web/dto/DayBudgetResponseDTO.java
  src/main/java/umc/haruchi/web/dto/MonthBudgetRequestDTO.java
  src/main/java/umc/haruchi/web/dto/MonthBudgetResponseDTO.java
Labels: :sparkles: Feat, :hammer: Fix

#37 [FIX] 전체 오류 수정
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/MonthBudget.java
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/service/MemberService.java
Labels: :art: Style, :hammer: Fix

#38 [FIX] 회원가입 시 생성한 monthBudget 저장하는 코드 추가
  src/main/java/umc/haruchi/service/MemberService.java
Labels: :hammer: Fix

#41 [FEAT] 한달 예산 금액 조회 API 구현
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/service/MonthBudgetService.java
  src/main/java/umc/haruchi/web/controller/MonthBudgetController.java
  src/main/java/umc/haruchi/web/dto/MonthBudgetResponseDTO.java
Labels: :sparkles: Feat

#43 [FEAT] 한달 지출률 조회 API 구현
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/service/MonthBudgetService.java
  src/main/java/umc/haruchi/web/controller/MonthBudgetController.java
  src/main/java/umc/haruchi/web/dto/MonthBudgetResponseDTO.java
Labels: :sparkles: Feat, :hammer: Fix

#45 [FIX] 날짜별 예산 조회 수정
  src/main/java/umc/haruchi/service/DayBudgetService.java
Labels: :hammer: Fix

#48 [FEAT] 지출 영수증 관련 조회 API 구현
  src/main/java/umc/haruchi/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/haruchi/converter/BudgetRedistributionConverter.java
  src/main/java/umc/haruchi/domain/Member.java
  src/main/java/umc/haruchi/repository/DayBudgetRepository.java
  src/main/java/umc/haruchi/repository/ExpenditureRepository.java
  src/main/java/umc/haruchi/repository/IncomeRepository.java
  src/main/java/umc/haruchi/repository/PullMinusClosingRepository.java
  src/main/java/umc/haruchi/repository/PushPlusClosingRepository.java
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
  src/main/java/umc/haruchi/web/controller/BudgetRedistributionController.java
  src/main/java/umc/haruchi/web/dto/BudgetRedistributionRequestDTO.java
  src/main/java/umc/haruchi/web/dto/BudgetRedistributionResponseDTO.java
Labels: :sparkles: Feat

#46 [FEAT] 한 주 예산 금액 조회 API 구현
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/domain/MonthBudget.java
  src/main/java/umc/haruchi/service/MemberService.java
  src/main/java/umc/haruchi/service/MonthBudgetService.java
  src/main/java/umc/haruchi/web/controller/MonthBudgetController.java
  src/main/java/umc/haruchi/web/dto/MonthBudgetResponseDTO.java
Labels: :sparkles: Feat

#49 [FEAT] 남은 일정 및 금액 조회 API 구현
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/service/MonthBudgetService.java
  src/main/java/umc/haruchi/web/controller/MonthBudgetController.java
  src/main/java/umc/haruchi/web/dto/MonthBudgetResponseDTO.java
Labels: :sparkles: Feat

#50 [FIX] 한 주 예산 조회 리스트에 closingState추가, API 수정
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/enums/ClosingStatus.java
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
  src/main/java/umc/haruchi/web/controller/BudgetRedistributionController.java
  src/main/java/umc/haruchi/web/dto/MonthBudgetResponseDTO.java
Labels: :hammer: Fix

#52 [STYLE] MemberApiController 및 토큰 관련 class 설명 추가
  src/main/java/umc/haruchi/config/login/SecurityConfig.java
  src/main/java/umc/haruchi/config/login/auth/MemberDetail.java
  src/main/java/umc/haruchi/config/login/auth/MemberDetailService.java
  src/main/java/umc/haruchi/config/login/jwt/JwtAccessDeniedHandler.java
  src/main/java/umc/haruchi/config/login/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/umc/haruchi/config/login/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/haruchi/config/login/jwt/JwtExceptionHandlerFilter.java
  src/main/java/umc/haruchi/config/login/jwt/JwtUtil.java
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
Labels: :art: Style

#51 [FIX] 한 주 예산 금액 조회 로직 수정
  src/main/java/umc/haruchi/converter/DayBudgetConverter.java
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/domain/DayBudget.java
  src/main/java/umc/haruchi/domain/enums/ClosingStatus.java
  src/main/java/umc/haruchi/service/MonthBudgetService.java
Labels: :hammer: Fix

#54 [REFACTOR] 리프레시 토큰 삭제 및 액세스 토큰 만료 시간 삭제
  src/main/java/umc/haruchi/config/login/SecurityConfig.java
  src/main/java/umc/haruchi/config/login/jwt/JwtUtil.java
  src/main/java/umc/haruchi/service/MemberService.java
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
  src/main/java/umc/haruchi/web/dto/MemberResponseDTO.java
Labels: :recycle: : Refactor, :art: Style, :hammer: Fix

#55 [FIX} 오류 수정
  src/main/java/umc/haruchi/converter/DayBudgetConverter.java
  src/main/java/umc/haruchi/domain/enums/ExpenditureCategory.java
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/web/controller/DayBudgetController.java
  src/main/java/umc/haruchi/web/dto/DayBudgetRequestDTO.java
Labels: :hammer: Fix

#56 [FIX] localdate 코드 로직 수정
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
Labels: :hammer: Fix

#57 [FIX] 당겨쓰기 EVENLY옵션 로직 수정
  src/main/java/umc/haruchi/service/BudgetRedistributionService.java
Labels: :hammer: Fix

#58 [FIX] 회원 세이프박스 값 조회 시 DTO 반환
  src/main/java/umc/haruchi/converter/MemberConverter.java
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
  src/main/java/umc/haruchi/web/dto/MemberResponseDTO.java
  src/main/resources/application.yml
Labels: :hammer: Fix

#59 [CHORE] redis host 주석 수정
  src/main/resources/application.yml
Labels: :wrench: Chore

#60 [FIX] 날짜별 예산 조회 수정
  src/main/java/umc/haruchi/converter/DayBudgetConverter.java
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/web/controller/DayBudgetController.java
  src/main/java/umc/haruchi/web/dto/DayBudgetResponseDTO.java
Labels: :hammer: Fix

#61 [STYLE] swagger에 monthBudget 관련 api response 추가
  src/main/java/umc/haruchi/web/controller/MonthBudgetController.java
Labels: :art: Style

#62 [STYLE] DayBudgetService에 스웨거의 ApiResponse 설명 추가
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/web/controller/DayBudgetController.java
Labels: :art: Style

#63 [STYLE] MemberApiController에 swagger 관련 ApiReponse 추가
  src/main/java/umc/haruchi/web/controller/MemberApiController.java
Labels: :art: Style

#65 [FIX] 다음 달로 넘어갈 때 예산 재분배 로직 수정
  src/main/java/umc/haruchi/converter/MonthBudgetConverter.java
  src/main/java/umc/haruchi/service/DayBudgetService.java
  src/main/java/umc/haruchi/web/controller/DayBudgetController.java
Labels: :hammer: Fix
